### ISSUE TITLE
Could you please provide me with the sample of the files used in repo or examples?

### ISSUE THREAD

**Issue by MachineGUN001** [ZheLi-Lab-Collaboration/3D-SMGE#1]
Many thanks for providing such an interesting approach. Could you please provide me with a sample of the file used in the following command, including `agg_smi.smi`, and `smi_csv.csv`, and what header information should be included in the smi file? 

```bash

python ./property_Pred\ADMET/general_admet/admet-pred.py --smi_path ../data/agg_smi.smi --csv_path ../data/smi_csv.csv --admet_result_path ../data/final_admet.csv

```

I tried some smiles format. The error report suggests that the smiles read are wrong
[09:31:20] SMILES Parse Error: syntax error while parsing: SMILES
[09:31:20] SMILES Parse Error: Failed parsing SMILES 'SMILES' for input: 'SMILES'
many thanks

Sh-Y

**Comment by DreamMemory001** [comment]
Thank you for your interest in our project. `agg_smi.smi` is the common SMILES file format, `smi_csv.csv` is the file generated by the program after processing. No processing is required from you.
